baseURL = 'http://blog-c94.pages.dev/'
languageCode = 'en-us'
title = "Don't Fear Tech"
theme = "risotto"

[params.theme]
palette = "gruvbox-dark"
mode = "dark-mode"

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/eyalmor-ent/"


[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/eyalmor-ent/"

[taxonomies]
tag = "tags"
category = "categories"

