baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Don't Fear Tech"
theme = "risotto"

[params.theme]
palette = "gruvbox-dark"
mode = "dark-mode"

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/joeroe/risotto"

[[params.socialLinks]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://"


[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "Linkedin"
url = "https://"

[taxonomies]
tag = "tags"
category = "categories"